export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "ms. Sara Andersen",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "ms. Adina Barbosa",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "mr. Rudi Droste",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "mr. Emre Asikoglu",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "mr. Evan Carlson",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "miss. Edita Vestering",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "mr. Roberto Vega",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "ms. Carolina Lima",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "mr. Kent Brewer",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "mr. Friedrich-Karl Brand",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "adult Labrador retriever",
    photo: "assets/post/1.jpeg",
    date: "May 24 2020 21:53:17",
    userId: 1,
    like: 43,
    comment: 9,
  },
  {
    id: 2,
    desc : "@adventure.yuki frozen grass short-coated black do...",
    photo: "assets/post/2.jpeg",
    date: "May 24 2020 12:44:55",
    userId: 2,
    like: 16,
    comment: 1,
  },
  {
    id: 3,
    desc: "Two boys hug their dogs in a leaf pile in the fall...",
    photo: "assets/post/3.jpeg",
    date: "May 24 2020 01:52:32",
    userId: 3,
    like: 28,
    comment: 2,
  },
  {
    id: 4,
    desc: "Sleeping dogs lie two dogs lying on black textile",
    photo: "assets/post/4.jpeg",
    date: "May 23 2020 19:55:22",
    userId: 4,
    like: 19,
    comment: 3,
  },
  {
    id: 5,
    desc: "black and white Husky",
    photo: "assets/post/5.jpeg",
    date: "May 23 2020 03:05:03",
    userId: 5,
    like: 79,
    comment: 5,
  },
  {
    id: 6,
    desc: "ice caves in the wild landscape photo of ice near ...",
    photo: "assets/post/6.jpeg",
    date: "May 24 2020 14:44:17",
    userId: 6,
    like: 31,
    comment: 6,
  },
  {
    id: 7,
    desc: "Hiking with my dog in the woods. black labrador re...",
    photo: "assets/post/7.jpeg",
    date: "May 24 2020 05:56:11",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "Bone salt and pepper schnauzer puppy",
    photo: "assets/post/8.jpeg",
    date: "May 23 2020 21:42:22",
    userId: 8,
    like: 18,
    comment: 1,
  },
  {
    id: 9,
    desc: "Dog in a forest at sunset dog in forest with sun r...",
    photo: "assets/post/9.jpeg",
    date: "May 23 2020 05:27:12",
    userId: 9,
    like: 242,
    comment: 2,
  },
  {
    id: 10,
    desc: "Milo durmiendo después de un largo día de jugar en...",
    photo: "assets/post/10.jpeg",
    date: "May 22 2020 14:50:38",
    userId: 10,
    like: 17,
    comment: 12,
  },
];
